### ISSUE TITLE
is the server branch still active?

### ISSUE THREAD

**Issue by leipzig** [galaxyproject/galaxy-cloudman-playbook#6]
it looks like /scripts/install_tool_shed_tools.py has diverged significantly

**Comment by afgane** [comment]
It has - it's been moved to a more appropriate role. I've removed the dir now and linked to the new location of the script in 80c7ce0f40ecd5da9be5c23e89c31267b815f8e6

Also, the `server` branch is not maintained at the moment. It really wasn't in my plan to revive it due to the complexities of keeping both branches in sync. Plus, although I haven't looked into it to any extent, existence of repos such as the Planemo Machine (https://github.com/galaxyproject/planemo-machine) may be a better avenue for achieving this functionality.
